networks:
  supabase_network_chatbotui:
    driver: bridge

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=http://jth-ai-01.hj.se:3000
    networks:
      - supabase_network_chatbotui
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      ollama serve &
      sleep 5 &&
      ollama pull llama3 &&
      ollama pull mistral || true &&
      wait

  ui:
    image: chatbot-ui:latest
    container_name: ui-container
    networks:
      - supabase_network_chatbotui

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - supabase_network_chatbotui
    depends_on:
      - ollama
      - ui
    restart: on-failure

volumes:
  ollama-data:
